workspace = 1, layout:scrolling
windowrule = workspace 1, match:class app.zen_browser.zen
exec-once = ~/.config/hypr/scripts/browser-column-width.sh

scrolling {
    explicit_column_widths = 0.5, 1.0
}
bindd = SUPER SHIFT, T, Toggle window column width, layoutmsg, colresize +conf
