# Trivia:
#   `bindd` is actually `bind[d]` - `bind` command with `d` flag.
#   `d` flag will allow you to write a description for your bind.

# Swaps the two halves of the split - both horizontal and *vertical*
# To swap left-to-right focus the "bigger" window first
bindd = SUPER SHIFT, J, Swap split, layoutmsg, swapsplit

# Open terminal in a floating window
# `--app-id=org.omarchy.terminal` is automagically tagged as `tag +floating-window` in `$OMARCHY_PATH/default/hypr/apps/system.conf`
# The same file governs appearance of floating windows.
# My initial approach was to use "Executing with rules" approach, however reuseing exisiting Omarchy machinery looks cleaner
#   ..., exec, [float; rules...] uwsm-app -- xdg-terminal-exec ...
unbind = SUPER SHIFT, RETURN
bindd = SUPER SHIFT, RETURN, Terminal (floating), exec, uwsm-app -- xdg-terminal-exec --app-id=org.omarchy.terminal --dir="$(omarchy-cmd-terminal-cwd)"
