[vitis-ai]
image="nvidia/cuda:13.3.0-cudnn-devel-ubuntu24.04"
hostname="vitis-ai"
additional_flags="--runtime=nvidia"
additional_flags="--gpus all"
# Create volume and subdirectories first:
# $ docker volume create ubuntu24.04-apt-cache
# $ docker run --rm --mount src=ubuntu24.04-apt-cache,dst=/var/task nvidia/cuda:13.3.0-cudnn-devel-ubuntu24.04 mkdir -p /var/task/var/cache/apt /var/task/var/lib/apt
additional_flags="--mount src=ubuntu24.04-apt-cache,dst=/var/cache/apt,volume-subpath=var/cache/apt"
additional_flags="--mount src=ubuntu24.04-apt-cache,dst=/var/lib/apt,volume-subpath=var/lib/apt"
