[general]
destination = "$XDG_CONFIG_HOME/hypr/_monitors.conf"

[power_events]

[power_events.dbus_query_object]
path = "/org/freedesktop/UPower/devices/line_power_AC0"

[[power_events.dbus_signal_match_rules]]
object_path = "/org/freedesktop/UPower/devices/line_power_AC0"


[profiles.home]
config_file = "hyprconfigs/home.go.tmpl"
config_file_type = "template"
[profiles.home.conditions]
[profiles.home.static_template_values]
mode = "second_screen"
rr_samsung = "144"
rr_laptop = "60"
scale_samsung = "1.25"
scale_laptop = "1.67"

[[profiles.home.conditions.required_monitors]]
description = "Chimei Innolux Corporation 0x1540"
monitor_tag = "laptop"

[[profiles.home.conditions.required_monitors]]
description = "Samsung Electric Company LC32G7xT H4ZN900002"
monitor_tag = "samsung"


[profiles.laptop]
config_file = "hyprconfigs/laptop.go.tmpl"
config_file_type = "template"
[profiles.laptop.conditions]

[[profiles.laptop.conditions.required_monitors]]
description = "Chimei Innolux Corporation 0x1540"
monitor_tag = "laptop"
