[general]
destination = "$XDG_CONFIG_HOME/hypr/_monitors.conf"

[power_events]

[power_events.dbus_query_object]
path = "/org/freedesktop/UPower/devices/line_power_AC0"

[[power_events.dbus_signal_match_rules]]
object_path = "/org/freedesktop/UPower/devices/line_power_AC0"


[profiles.second-screen]
config_file = "$XDG_CONFIG_HOME/hyprdynamicmonitors/hyprconfigs/second-screen.go.tmpl"
config_file_type = "template"
[profiles.second-screen.conditions]

[[profiles.second-screen.conditions.required_monitors]]
description = "Chimei Innolux Corporation 0x1540"
monitor_tag = "monitor0"

[[profiles.second-screen.conditions.required_monitors]]
description = "Samsung Electric Company LC32G7xT H4ZN900002"
monitor_tag = "monitor1"


[profiles.pc-screen]
config_file = "$XDG_CONFIG_HOME/hyprdynamicmonitors/hyprconfigs/pc-screen.go.tmpl"
config_file_type = "template"
[profiles.pc-screen.conditions]

[[profiles.pc-screen.conditions.required_monitors]]
description = "Chimei Innolux Corporation 0x1540"
monitor_tag = "monitor0"
